version: "3.0"

services:
  solr:
    container_name: "milkensolr-solr"
    image: milken/solr
    build: 
      context: ./solr
    env_file:
      - .env
    environment:
      - HOST=milkensolr-nginx
    networks:
     - solr-network
    expose:
      - "8983"
    ports:
      - "8983:8983"

  solr-proxy:
    container_name: "milkensolr-nginx"
    image: milken/solr-proxy
    build: ./solr-proxy
    links:
      - solr
    networks:
      - solr-network
    external_links:
      - solr-ssl_solr-network:php
    environment:
     - "SOLR_URL=http://milkensolr-solr:8983/solr/discovery"
     - "HOST=milkensolr-nginx"
    expose:
      - "8443"
      - "8983"
    ports:
      - "8443:8443"
    depends_on:
      - solr
      - events-api

  events-api:
    container_name: "milkensolr-events-api"
    image: milken/events-api:latest
    networks:
      - solr-network
    expose:
      - "9000"
    env_file:
      - .env
    environment:
      - "DATABASE_URL=sqlsrv://${GRID_MSSQL_USERNAME}:${GRID_MSSQL_PASSWORD}@${GRID_MSSQL_IP}:${GRID_MSSQL_PORT}/${GRID_MSSQL_DBNAME}?CharacterSet=UTF-8"
      - "APP_ENV=prod"


networks:
  solr-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
