version: "3.7"

services:
  solr:
    container_name: "milkensolr-solr"
    image: milken/solr
    build: 
      context: ./solr
    env_file:
      - .env
    environment:
      - HOST=milkensolr-nginx
    networks:
     - solr-network
    expose:
      - "8983"
    ports:
      - "8983:8983"

  solr-proxy:
    container_name: "milkensolr-nginx"
    image: milken/solr-proxy
    build: ./solr-proxy
    links:
      - solr
    networks:
      - solr-network
    external_links:
      - solr-ssl_solr-network:php
    environment:
     - "SOLR_URL=http://milkensolr-solr:8983/solr/discovery"
     - HOST=milkensolr-nginx
    expose:
      - "8443"
      - "8983"
    ports:
      - "8443:8443"
    depends_on:
      - solr

networks:
  solr-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
