version: "3.7"

services:
  solr-proxy:
    container_name: solr-nginx-proxy
    build: .
    networks: 
     - solr-network
    environment:
     - "SOLR_URL=http://solr:8983/solr/discovery"
    ports:
     - 8443:8443

networks:
  solr-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
