language: bash

services:
- docker

env:
  matrix:
  - SOLR_VER=8.4.1 TAGS=8.4,8,latest
  - SOLR_VER=7.7.2 TAGS=7.7,7
  - SOLR_VER=7.6.0 TAGS=7.6
  - SOLR_VER=7.5.0 TAGS=7.5
  - SOLR_VER=6.6.6 TAGS=6.6,6
  - SOLR_VER=5.5.5 TAGS=5.5,5

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
